global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'sonarqube'
    static_configs:
    - targets: ['localhost:9000']
  - job_name: 'jenkins'
    static_configs:
    - targets: ['localhost:8081']